export const ENTER_CITY = 'ENTER_CITY';
export const CLICK_HISTORY_BUTTON = 'CLICK_HISTORY_BUTTON';
export const CLOSE_SEARCH_HISTORY = 'CLOSE_SEARCH_HISTORY';
export const ADD_WEATHER_TO_HISTORY = 'ADD_WEATHER_TO_HISTORY';